spring:
  application:
    name: friends
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://madcampfriends.cv3dstdglqkx.ap-northeast-2.rds.amazonaws.com
    username: root
    password: madcampFriends0103
  sql :
    init :
      mode : never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000